### ISSUE TITLE
Version number not incrementing correctly

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1403]
@muloem @jonase @janagombitova I think this might be the issue Aulia reported recently where the versioning was not working as he expected.

When the following happens:
- Open a previously published survey
- Change the form name or survey name
- Perform some action which should increment the version number (i.e. edit a question, add a question, delete a question).
- The version number is not incremented, but the changes can be successfully published

If the changing the form name step is skipped, then the version number is updated correctly when any of the specified actions occur.

**Comment by janagombitova** [comment]
Possibly related to this issue, is one Jigmy pointed out - the 'Modified' date does not change in the survey list with minor changes as re-defining a question name. @muloem Can we look into both issues at once?

**Comment by ichinaski** [comment]
Somewhat related: When updating a cascade resource, any form linked to such cascade needs to be republished, in order to see the changes reflected on the form definition. However, if the form status is *PUBLISHED*, this means the user needs to perform a change to the survey, before the **publish** button becomes enabled (and therefore its version incremented).

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5744](http://flowhelp.akvo.org/discussions/problems/5744-fw-updating-the-questionnaire).

**Comment by muloem** [comment]
The issue of having to republish surveys is also reported under #1118.

**Comment by janagombitova** [comment]
When looking at all the comments in this issue we touch upon these things: 
1. survey version number does not change properly after republishing 
2. modified date not changing accordingly (will create an issue after I confirm the problem)
3. need to republish a survey after making changes in cascades https://github.com/akvo/akvo-flow/issues/1118

As the three items are quite separate issues, I propose that for this issue we deal with point **1. survey version number does not change properly after publishing** and leave the other points to be dealt with in the separate issues

**Comment by janagombitova** [comment]
So I was trying to reproduce the above mentioned problem: after making changes to the form the version number does not change. I could not. With each attempt once the change was fully saved, the version number increased. I did find a problem with the publish button. 

Considering I was not able to reproduce this issue, I will close it for now and note it down for the time being, to observe and not forget.

**Comment by janagombitova** [comment]
## Current situation 
As far as I understand, the version number grows and the publish button is activated once the user makes an appropriate change. This is the expectation. Below is a list of how things work currently

Action | version number change? | trigger to republish? |
------------ | -------- | -------------
change survey title | no | no
change survey privacy | no | no
change survey language | no | no
enable monitoring | no | no
change set registration form | no | no
change form name | no | yes 
add new translation to form | yes | yes 
change existing translation (anything) | yes | yes 
add new question group | yes | yes 
rename existing question group | yes | yes 
delete question group | yes | yes 
copy question group | yes |yes
move question group | yes | yes 
make question group repeatable | yes | yes  
change question group from repeatable to not repeatable | yes | yes 
add new question | yes | yes 
delete existing question | yes | yes
change any question setting (name, dependency, option, mandatory...) | yes | yes  
copy question | yes | yes
move question | yes | yes 

All changes that happen individually on the form level trigger version and publishing. There are however two questions/issues that need our attention 

## Issue 1
The question we need to answer here is: Do we want changes to the survey definition trigger a need to republish all forms within that survey? If not (and we keep the logic as it is), then we only need to look at **Issue 2** 

For the user, especially changes related to monitoring need to be reflected on the app, so the user currently makes a "fake" change on the form level, to then on the app see that changes to monitoring settings. 

## Issue 2 
The issue is that once you publish, you need to leave the survey and then some back again to see that the publish button is not enabled anymore. So if you make a change, then publish and remain on the survey page, and then make further changes, the version number does not grow properly. 

![version number](https://cloud.githubusercontent.com/assets/12456965/23306893/b1568134-faa5-11e6-9929-814e13a3c49c.gif)

This causes confusion. Ideally the version number change and enabling of the publish button should be triggered every time a user makes an appropriate change > publishes > change > version change and publish enabled.

**Comment by kymni** [comment]
Was able to reproduce part of the issue where changing the form name triggers publish but doesn't change the version number. Fix for this is setting the "NOT_PUBLISHED" status for the form when name changes so that when commit is done, version number will also change

**Comment by muloem** [comment]
As a note. This fixes partially the issue but not all aspects are addressed. We need to take a look at the rest.

**Comment by janagombitova** [comment]
Confirming that the version number does update if the user changes and saved the form name. The publish status also changes as expected. 

Considering the full issue is not yet resolved I suggest we keep it open. I will try to find patterns in survey form edits that still need to be addresses to ensure that the version number updates correctly.

**Comment by janagombitova** [comment]
To make our lives easier I have split handling the **once you publish, you need to leave the survey and then some back again** related issue away from this issue to here: https://github.com/akvo/akvo-flow/issues/2488

This issue should then focus only on ensuring that once a survey form is published and Petra makes a change to the form the version number changes and publishing is enabled. So just to be sure did a task --> checked the version updated --> published --> checked it is published in messages --> went back to the form --> did another task. All worked well for (all actions tested separately but written in bulk to save space): 
- creating a new group, moving a group, changing a group name, copying a group, deleting a group
- creating a question, moving a questions, copying a question, deleting a question
- adding a new translation and saving, editing a translation and saving 
- changing data point name setting on question (on and off) and saving 
- changing mandatory setting on question (on and off) and saving 
- changing question text, variable name, type and saving 
- changing question settings and saving

From what I can see the version number increments correctly. I feel by that resolving the issue around publishing we will tackle the case where confusion might happen (I publish, but do not navigate away and continue editing the form) 

I do not know what else to do in regards to this issue.

**Comment by janagombitova** [comment]
After some more testing I can for now conclude that the issue present is due to Salim making changes to the form > hitting publish > staying on the page (not going to the messages tab) > making more changes to the survey form > hitting publish again. Then the version number does not update as he did not refresh his screen. For this problem we have issue #2488 

Thus closing this issue for now. If other problems arise, we can always reopen the issue
