### ISSUE TITLE
Remove icons that do not provide extra value

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1871]
With the Flow dashboard clean up we decided to remove the icons that do not provide any extra value (information) to the user. The goal is to declutter the dashboard and simplify the screen as much as possible. With this issue we will identify which icons can be removed.

**Comment by janagombitova** [comment]
Currently we have icons in these places of the dashboard: 
- **main menu** - in combination with text 
- **breadcrumb** - starts with a folder icon (but different than to one we have on Surveys in the main menu) 
**in list of folders:** 
   - pencil icon (no text) - to change the name of the folder
   - folder icon (no text) - does not trigger an action, but indicates to the user if the folder is empty or not 
   - arrows icon (no text) - to move the position of the folder 
   - trash bin icon (no text) - to remove an empty folder 
- **in list of surveys:**
   - pencil icon (no text) - to edit the survey (same action as if you click on the survey name)
   - arrows icon (no text) - to move the survey 
   - files icon (no text) - to copy the survey 
- **inside a survey** 
   - save button - in combination with text 
   - plus icon with Add new forms - in combination with text - to add new forms 
   - in the forms title with the name of the form - no function 
![screen shot 2017-02-14 at 16 40 30](https://cloud.githubusercontent.com/assets/12456965/22935945/5289e1c4-f2d4-11e6-88fd-33c55e93f7b4.png)
- **in a question group/question**
   - plus with Insert group here - in combination with text 
   - arrow with Add new question - in combination with text  
   - pencil with Edit - in combination with text - to open up a question and start editing it, this is not possible by clicking on the question name (as with surveys)
   - arrows with Move - in combination with text - to move the questions around 
   - files icon with Copy - in combination with text - to copy a question 
   - trash can with Delete - in combination with text - to delete a question 
- **in Assignments list**
   - pencil icon (no text) - to edit an existing assignment (not possible to open up an assignment in a different way) 
   - circular minus icon (no text) - to remove an assignment 
   - *NOTE: in some other tables, these actions are triggered by text links: Edit, Delete*
- **Cascade resources** 
   - cascade icon in the middle of the page 
   - plus icon with Add new cascade - in combination with text
   - floppy disk icon with Publish - in combination with text 
   - trash can icon with Delete - in combination with text
   - download icon with Import cascade data - in combination with text 
   - plus icon with Add level - in combination with text
   - pencil icon (no text) - next to each level to edit its name 
   - pencil icon (no text) - for each item in a level to edit its name 
   - delete icon (no text) - for each item in a level to delete it 
   - circular arrow with Move left/right - in combination with text
- ** User list**
   - plus icon with Add new user - in combination with text
   - pencil icon with Edit - in combination with text
   - x icon with Delete - in combination with text
- **when editing a particular user**
   - pencil icon with Editing - in subtitle of a page, no function
   - circular arrow icon with Go back - in combination with text 
   - floppy disk with Save user info - in combination with text 
   - x icon with Delete - in combination with text, to remove each role for a user 
   - looping arrows (not sure how it is called) with (Re)generate - in combination with text, under the Manage API keys
   - no entry icon with Revoke - in combination with text
- **Roles & Permissions** 
   - plus icon with Add new role - in combination with text
   - pencil icon with Edit - in combination with text
   - x icon with Delete - in combination with text 
- **when editing a role**
   - pencil icon with Edit - in the subtitle of a page, no function 
   - arrow with Go back - in combination with text 
   - floppy disk with Save permissions set - with text
   - x with cancel - in combination with text

**Comment by janagombitova** [comment]
@loicsans I took a look at beta1 and I like that the header with the main tabs is much cleaner now and like the home icon in the beginning of the breadcrumb 👍 

Also I must say I like the change of the icons to text in the list of surveys and folders. I have two comments here though:
- for the survey, could we alight the `edit`; `move` etc texts with the survey name. I fid them a bit off in the middle of the text box as they are currently 
- it seems as if they have a "invisible" box around them, in a similar colour of the survey background but a darker shade. Can you remove that? 

<img width="1277" alt="screen shot 2017-04-07 at 14 06 33" src="https://cloud.githubusercontent.com/assets/12456965/24799555/17b48e96-1b9c-11e7-84f0-3d7ad8cea4c8.png">

Inside a survey the save button; and add new forms should not have the icon anymore according to the checklist, but I still see it on beta1. 

You removed the form icon in the form tabs, but now the name is not starting from the beginning of the tab. Can you align the form title more to the left? 

<img width="711" alt="screen shot 2017-04-07 at 14 23 06" src="https://cloud.githubusercontent.com/assets/12456965/24799847/bc4522d0-1b9d-11e7-975f-9d47139a6718.png">

In Assignments list I think we should also go for text instead (edit and delete) of the pencil icon and the minus icon. What do you think? 

In cascades, is there a reason why you decided to keep the pencil and trash bin for the cascade levels? 

With the User tab I assume it is the same story as with why the table colours are not updated yet, right?

**Comment by loicsans** [comment]
I have addressed all the issues mentionned above.

**Comment by janagombitova** [comment]
@loicsans crossed checked beta1 and here are a few items to look into: 

The edit, move and copy links are better now in the survey list, but when you hover over them the text changes to orange as it should, but a area is highlighted as well, what does not happen if you hover over other clickable links. Can you unify it please? 

<img width="1061" alt="screen shot 2017-04-10 at 14 11 51" src="https://cloud.githubusercontent.com/assets/12456965/24861079/afaa32e8-1df7-11e7-9312-e4af9ad6748c.png">

When a user creates a new survey there is a form icon. Are we going to keep it? It is not in the list above.  The Add new forms button is not aligned as there is a free space in the button before the text starts. 

<img width="1110" alt="screen shot 2017-04-10 at 14 14 07" src="https://cloud.githubusercontent.com/assets/12456965/24861227/40874e72-1df8-11e7-8069-6d2d070b962b.png">

In the Assignments, please change the word "remove" to "delete" as we use delete all across the dashboard and not remove. 

In the Assignments, can you put the two actions next to each other as we have in other parts of the dashboard? 

<img width="1070" alt="screen shot 2017-04-10 at 14 21 22" src="https://cloud.githubusercontent.com/assets/12456965/24861449/10e08aca-1df9-11e7-9f80-2853642cc64a.png">

The change from icon to text is cascades cause the same thing as in the survey list, that the text links now have a background box. Can you remove that please? 
<img width="542" alt="screen shot 2017-04-10 at 14 22 34" src="https://cloud.githubusercontent.com/assets/12456965/24861581/915291bc-1df9-11e7-8c30-d27ede868003.png">

**Comment by janagombitova** [comment]
@loicsans the edit, move and copy links still show the box when hovering over in the survey list 

<img width="1061" alt="screen shot 2017-04-10 at 14 11 51" src="https://cloud.githubusercontent.com/assets/12456965/24861079/afaa32e8-1df7-11e7-9312-e4af9ad6748c.png">

**Comment by janagombitova** [comment]
I have created another separate issue that relates to changes here: https://github.com/akvo/akvo-flow/issues/2065

**Comment by janagombitova** [comment]
👍  considering the only found issue is handled and fixed in the issues linked above, this is ready to go. I expect users needing some adjustment time, but I think these are really good subtle changes
